@startuml

entity character
entity health
entity level
entity alive
entity dead
entity status
entity position
entity maxRange
entity distance

entity characterAction
entity doDamage
entity heal

character *--> health
character *--> level
character *--> status
character *--> position
character *--> maxRange

status <|-- alive
status <|-- dead

character --> "hace" characterAction

characterAction <|-- doDamage
characterAction <|-- heal

status --> "cuando está a 0" health

doDamage --> "disminuye" health
heal --> "aumenta" health
doDamage ..> maxRange
doDamage ..> distance
distance *--> "2" position

@enduml
